---
- name: webcontent
  hosts: dev
  become: true
  tasks:
    - name: Create dev host group
      ansible.builtin.group:
        name: webdev
        state: present
    - name: Create directory /webdev
      ansible.builtin.file:
        path: /webdev
        state: directory
        group: webdev 
        mode: '0775'
        setype: httpd_sys_content_t
    - name: Create file
      ansible.builtin.copy:
        content: "Development"
        dest: /webdev/index.html
        setype: httpd_sys_content_t
    - name: Create the symbolic link
      ansible.builtin.file:
        src: /webdev/index.html
        dest: /var/www/html/webdev
        state: link
        force: true
    - name: Make sure the service is started
      ansible.builtin.service:
        name: httpd
        state: started

