---
- name: Update myhosts on dev server
  become: true
  hosts: all
  tasks:
  - block:
    - name: Use template hosts.j2
      ansible.builtin.template:
       src: hosts.j2
       dest: /etc/myhosts
    - name: add content to myhosts file
      ansible.builtin.lineinfile:
       path: /etc/myhosts
       line: "{{hostvars[item].ansible_default_ipv4.address}} {{hostvars[item].ansible_fqdn}} {{hostvars[item].ansible_hostname}}"
      loop: "{{groups['all']}}"
    when: inventory_hostname in groups['dev']

