---
- name: Install php and mariadb
  hosts: dev,test,prod
  become: true
  vars:
    packages:
      - php
      - mariadb
  tasks:
    - name: Install php and mariadb
      ansible.builtin.yum:
        name: "{{item}}"
        state: latest
      loop: "{{packages}}"
    - name: Install RPM Development tools
      ansible.builtin.yum:
        name: "@RPM Development Tools"
        state: latest
      when: inventory_hostname in groups['dev']
    - name: Update all packagesto the latest version
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: inventory_hostname in groups['dev']
