---
- name: configure repos
  hosts: all
  become: true
  tasks:
    - name: BaseOS
      ansible.builtin.yum_repository:
       name: BaseOS Repo
       description: base software
       baseurl: http://controller/rheldvd90/BaseOS/
       gpgcheck: yes
       gpgkey: http://controller/rheldvd90/RPM-GPG-KEY-redhat-release
       enabled: yes

    - name: AppStream
      ansible.builtin.yum_repository:
       name: AppStream Repo
       description: stream software
       baseurl: http://controller/rheldvd90/AppStream/
       gpgcheck: yes
       gpgkey: http://controller/rheldvd90/RPM-GPG-KEY-redhat-release
       enabled: yes

