---
- name: VLAN 382
  hosts: servers
  gather_facts: false
  become: true
  vars:
        ansible_ssh_user: "{{ user }}"
        ansible_ssh_pass: "{{ pass }}"
        env: "OP"
        user: "dt84268a"

  vars_prompt:
      - name: "user"
        prompt: "User"
        private: no
      - name: "pass"
        prompt: "Enter password"
        private: yes


  tasks:
    - name: Create reboot folder
      ansible.builtin.file:
        path: "/root/reboot-ansible"
        state: directory
        mode: "0755"
    - name: Execute commands 
      ansible.builtin.shell:
        cmd: "{{item}}"
      loop: 
        -  df -TPh > /root/reboot-ansible/df.ph
        -  mount > /root/reboot-ansible/mount
        -  route -n > /root/reboot-ansible/route.n
        -  cat /etc/fstab > /root/reboot-ansible/fstab
        -  cp /etc/sysconfig/network-scripts/ifcfg* /root/reboot-ansible
    - block:
      - name: Get the interface name
        ansible.builtin.shell:
          cmd: "nmcli device show | grep 'GENERAL.DEVICE'| head -n 1 | awk '{print $2}'"
        register: interface
      - name: Remove old config
        ansible.builtin.lineinfile:
          path: /etc/sysconfig/network-scripts/ifcfg-{{interface.stdout}}
          state: absent
          regexp: '^.*\b{{item}}\b.*$'
        loop: [IPADDR,GATEWAY,NETMASK,PREFIX,DNS1,DNS2,DNS3]
      - name: Change new config
        ansible.builtin.lineinfile:
          path: /etc/sysconfig/network-scripts/ifcfg-{{interface.stdout}}
          state: present
          line: "{{item}}"
        loop: 
          - IPADDR={{new_ip}}
          - GATEWAY=10.30.64.1
          - NETMASK=255.255.240.0
          - DNS1=10.210.87.132
          - DNS2=10.108.194.14
          - DNS3=128.23.1.8
      tags:
        - never
        - conf
      ignore_errors: no

    - name: Mount fs
      ansible.builtin.command:
        cmd: "mount -av"
      tags:
        - never 
        - mount
    - name: Shutdown the servers
      ansible.builtin.command:
        cmd: "shutdown -h now"
      tags:
        - never
        - poweroff
    - name: Ping the servers
      ansible.builtin.ping:
      tags:
        - never
        - ping
    - name: Connect it
      ansible.builtin.shell: |
         cd /root
         curl -O http://s11280k0/pub/bootstrap.py
         chmod +x bootstrap.py
         subscription-manager clean
         /usr/libexec/platform-python bootstrap.py --login={{user}} --password={{user}} --server s11280k0.snm.snecma --location='Worldwide' --organization='Safran Aircraft Engines' --hostgroup='Linux-VM/{{env}}/VLAN382/RHEL8' --activationkey="RHEL8.X" --force --install-katello-agent
      tags:
        - never
        - satt
